### ISSUE TITLE
Google Drive does not prompt for credentials

### ISSUE THREAD

**Issue by tevenan** [batteryshark/jeopardy_sync#1]
Followed commented configuration instructions.
Google Drive API does not prompt for credentials.
Receive the following error:

`C:\Python27\lib\site-packages\oauth2client_helpers.py:255: UserWarning: Cannot access C:\Users\USERNAME\JeopardyDownloadSync.credentials\Storage.json: No such file or directory warnings.warn(_MISSING_FILE_MESSAGE.format(filename)) Re Authenticate Traceback (most recent call last): File "jeopardy_sync.py", line 77, in <module> drive_service = gdrive.drive_create(DRIVE_NICKNAME) # Change this File "C:\Users\USERNAME\JeopardyDownloadSync\gdrive.py", line 75, in drive_create credentials = get_credentials(drive_name) File "C:\Users\USERNAME\JeopardyDownloadSync\gdrive.py", line 64, in get_credentials flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES) File "C:\Python27\lib\site-packages\oauth2client_helpers.py", line 133, in positional_wrapper return wrapped(args, *kwargs) File "C:\Python27\lib\site-packages\oauth2client\client.py", line 2135, in flow_from_clientsecrets cache=cache) File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 165, in loadfile return _loadfile(filename) File "C:\Python27\lib\site-packages\oauth2client\clientsecrets.py", line 125, in _loadfile exc.strerror, exc.errno) oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'csec.json', 'No such file or directory', 2)`

**Comment by tevenan** [comment]
Error caused by Python 2.7.
Project must be ran using Python 3.
