### ISSUE TITLE
run_jsync.py throws AttributeError: type object 'Path' has no attribute 'home'

### ISSUE THREAD

**Issue by mastermargie** [batteryshark/jeopardy_sync#2]
```
$ python ./bin/run_jsync.py
Traceback (most recent call last):
  File "./bin/run_jsync.py", line 2, in <module>
    from jeopardy_sync import JSync
  File "/usr/lib/python2.7/site-packages/jeopardy_sync-1.1-py2.7.egg/jeopardy_sync/__init__.py", line 4, in <module>
    from jeopardy_sync.gdrive import GDriveClient
  File "/usr/lib/python2.7/site-packages/jeopardy_sync-1.1-py2.7.egg/jeopardy_sync/gdrive.py", line 18, in <module>
    DEFAULT_SERVICE_ROOT = os.path.join(str(Path.home()), '.gdrive')
AttributeError: type object 'Path' has no attribute 'home'
```

**Comment by mastermargie** [comment]
Looks like the application isn't compatible with Python 2.x. Ran fine with 3.x

**Comment by tevenan** [comment]
Sorry to hijack, do you have any suggestions for issue #1?
For some reason, I'm not getting prompted for google account details.
